[/Script/Engine.RendererSettings]
; For VisionOS, these must be enabled in both IOSEngine.ini & VisionOSEngine.ini because as of UE 5.5.3 at 
; cook time, FShaderPlatformCachedIniValue maps EShaderPlatform::SP_METAL to ios rather than visionOS
vr.MobileMultiView=True
